### PR TITLE
Prepare data

### PR DESCRIPTION
**Pull request by Emad78**
Hi. I hope have a good weekend.
data preparation is done for next steps. Arman dataset and EmoPars dataset aggregated together with same labeling and unlabeled data have been removed.

### CODE REVIEW

**Review by ZahraArshia — CHANGES_REQUESTED** [review]
# STATUS: REQUEST CHANGES ⚠️ 
image

Hello @Emad78, @MaryamNourii and @AmirRezaEskandarani 😃 
Nice job changing EmoPars into single label form and merging two datasets together 👍
Although there is still one more step to go! Your dataset only have one column including both text and label looking like this now:
image
or:
image

It would be better if we can have a two column dataset, one column for the text and the other for the label, something like this:
image

**Comment by Emad78** [comment]
Hi
That's true, but when I load data with pandas, dataset has two column. I don't understand problem😅😅

**Comment by ZahraArshia** [comment]
Here, in the last line you merged two columns together :
image

**Comment by Emad78** [comment]
In the last line, I select that columns. But when I change this line, result doesn't have any changes. I think this problem is for mistake of multiple rows. I check dataset and report😅

**Pull request merged**
